### ISSUE TITLE
Ajuda com Tipagem

### ISSUE THREAD

**Issue by FranciscoMaik** [fbssistemas/realm-rn#1]
Olá, tudo bem pessoal?

Eu venho procurando esse conteúdo em inumeros locais e não estou conseguindo resultado, até conseguir encontrar este repo.
Desculpe está abrindo essa Issue, mas poderia me dar uma ajuda na questão de fazer a consulta de busca no banco e colocar em um estado.

Por exemplo:
~~~ javascript
const data = realm.objects('Product').sorted('created', true);
setProducts(data)
~~~

Eu criei as interfaces utilizando a mesma ideia de vocês.

E minha váriavel para armazenar é a seguinte:
~~~ javascript
const [products, setProducts] useState<IProduct[]>([]);
~~~

No entanto quando estou setando recebo o seguinte erro:

```
O argumento do tipo 'Results<Object>' não é atribuível ao parâmetro do tipo 'SetStateAction<IProduct[]>'.
  O tipo 'Results<Object>' não tem as propriedades a seguir do tipo 'IProduct[]': pop, push, reverse, shift e mais 6.
```

Desde já agradeço!

**Comment by guilherme4072** [comment]
Agradecemos por abrir essa issue, corrigimos a pouco a tipagem.
alterar de:
~~~ typescript
const [products, setProducts] useState<IProduct[]>([]);
~~~
para:
~~~ typescript
const [products, setProducts] useState<Product[]>();
~~~

*alterado o model product
